server:
  port: 8888
spring:
  application:
    name: microservice-gateway-zuulfilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
