server:
  port: 9082
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: microservice-consumer-movie-feign-hystrix-fallback-stream,microservice-consumer-movie-feign-hystrix-dashboard,microservice-consumer-movie-ribbon-hystrix
  cluster-name-expression: "'default'"