server:
  port: 9085
spring:
  application:
    name: microservice-consumer-movie-ribbon-hystrix
  rabbitmq:
    host: 192.168.10.21
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: hystrix.stream
