server:
  port: 8888
spring:
  application:
    name: microservice-gateway-zuul-file-upload
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000


