spring:
  application:
    name: microservice-discovery-eureka-cluster
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8761/eureka/,http://eureka02:8762/eureka/,http://eureka03:8763/eureka/
---
spring:
  profiles: eureka01
server:
  port: 8761
eureka:
  instance:
    hostname: eureka01
---
spring:
  profiles: eureka02
server:
  port: 8762
eureka:
  instance:
    hostname: eureka02
---
spring:
  profiles: eureka03
server:
  port: 8763
eureka:
  instance:
    hostname: eureka03
