server:
  port: 9082
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-turbine-mq
  rabbitmq:
    host: 192.168.10.21
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true