server:
  port: 9081
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
     service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
     com.sugelamei.client.UserFeignClient: debug
#代码和配置二选一
feign:
  client:
    config:
      microservice-consumer-movie-feign:
        loggerLevel: full


