server:
  port: 8761

spring:
  security:
    user:
      name: user
      password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://user:1234@localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
